In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
r=requests.get("https://www.census2011.co.in/census/state/maharashtra.html")
c=r.content
#type(c)

In [3]:
soup=BeautifulSoup(c,"html.parser")
print(soup.prettify())
type (soup)

<!DOCTYPE html>
<html>
 <head>
  <title>
   Maharashtra Population Sex Ratio in Maharashtra Literacy rate data 2011-2019
  </title>
  <meta content="Population of Maharashtra in 2019 increased to 12.35 Crore from 11.24 Crores figure of 2011 census. Literacy rate in Maharashtra is 82.34 percent while sex ratio is 929 females per 1000 males." name="Description"/>
  <link href="https://www.census2011.co.in/census/state/maharashtra.html" rel="canonical"/>
  <script type="text/javascript">
   $(document).ready(function(){$('#filter').DataTable({"asSorting":["desc"],"aTargets":[2]});});
  </script>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <meta content="index, follow" name="robots"/>
  <link href="/css/A.bootstrap.min.css.pagespeed.cf.C0bEaOj2-a.css" media="all" rel="stylesheet" type="text/css"/>
  <script async="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">
  </script>
  <script>
   (adsbygoogle=window.adsbygoogle||[]).push({google_ad_client:"ca-pub-0612465356921996",enable_page_level_ads:true});
  </script>
 </head>
 <body>
  <!-- Navigation Bar Sticky -->
  <nav class="navbar navbar-inverse navbar-fixed-top sticky">
   <div class="container-fluid">
    <div class="navbar-header">
     <button class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">
       Toggle navigation
      </span>
      <span class="icon-bar">
      </span>
      <span class="icon-bar">
      </span>
      <span class="icon-bar">
      </span>
     </button>
     <a class="navbar-brand" href="//www.census2011.co.in/">
      Census 2011
     </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav">
      <li>
       <a href="/">
        Home
       </a>
      </li>
      <li class="active">
       <a href="/states.php">
        States
       </a>
      </li>
      <li>
       <a href="/district.php">
        District
       </a>
      </li>
      <li class="dropdown">
       <a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">
        Cities/Towns
        <span class="caret">
        </span>
       </a>
       <ul class="dropdown-menu" role="menu">
        <li>
         <a href="/urbanagglomeration.php" title="Metropolitan Cities">
          Metropolitan (UA)
         </a>
        </li>
        <li class="divider">
        </li>
        <li>
         <a href="/city.php" title="Cities of India">
          Cities
         </a>
        </li>
        <li class="divider">
        </li>
        <li>
         <a href="/towns.php" title="Towns">
          Towns
         </a>
        </li>
       </ul>
      </li>
      <li>
       <a href="/religion.php">
        Religion
       </a>
      </li>
      <li class="dropdown">
       <a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">
        Data
        <span class="caret">
        </span>
       </a>
       <ul class="dropdown-menu" role="menu">
        <li>
         <a href="/religion.php" title="Religion">
          Religion
         </a>
        </li>
        <li>
         <a href="/literacy.php" title="Literacy">
          Literacy
         </a>
        </li>
        <li>
         <a href="/sexratio.php" title="Sex Ratio">
          Sex Ratio
         </a>
        </li>
        <li>
         <a href="/density.php" title="Density">
          Density
         </a>
        </li>
        <li>
         <a href="/facts.php" title="Facts">
          Facts
         </a>
        </li>
        <li class="divider">
        </li>
        <li>
         <a href="/scheduled-castes.php" title="Scheduled Castes">
          Scheduled Castes
         </a>
        </li>
        <li>
         <a href="/scheduled-tribes.php" title="Scheduled Tribes">
          Scheduled Tribes
         </a>
        </li>
        <li class="divider">
        </li>
        <li>
         <a href="/hhassets.php" title="House Assets">
          House Assets
         </a>
        </li>
        <li>
         <a href="/houseless.php" title="House Less">
          House Less
         </a>
        </li>
        <li>
         <a href="/slums.php" title="Slums">
          Slums
         </a>
        </li>
        <li class="divider">
        </li>
        <li>
         <a href="/transgender.php" title="Transgender">
          Transgender
         </a>
        </li>
        <li>
         <a href="/marital.php" title="Marital Status">
          Marital Status
         </a>
        </li>
        <li>
         <a href="/fertility.php" title="Fertility Ratio">
          Fertility Ratio
         </a>
        </li>
        <li>
         <a href="/disability.php" title="Disability">
          Disability
         </a>
        </li>
       </ul>
      </li>
      <!--
		<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Facts <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
		  <li><a href="/p/glance.php">India at Glance</a></li>
          <li class="divider"></li>
		  <li><a title="Related to States" href="/facts/state.php">State Facts</a></li>
		  <li><a title="Related to Districts" href="/facts/district.php">District Facts</a></li>
		  <li><a title="Related to Metropolitan" href="/facts/urban.php">Metropolitan Facts</a></li>
		  <li><a title="Related to Cities" href="/facts/city.php">City Facts</a></li>
          </ul>
        </li>
-->
     </ul>
     <form action="/search.php" class="navbar-form navbar-left" id="cse-search-box">
      <div class="input-group">
       <input name="cx" type="hidden" value="partner-pub-0612465356921996:9964620645"/>
       <input name="cof" type="hidden" value="FORID:10"/>
       <input name="ie" type="hidden" value="UTF-8"/>
       <input class="form-control" id="search_key" maxlength="128" name="q" size="20" type="text" value=""/>
       <span class="input-group-btn">
        <button class="btn btn-default" id="submit" name="sa" style="margin-left:10px;" type="submit" value="Search">
         Submit
        </button>
       </span>
      </div>
     </form>
    </div>
   </div>
  </nav>
  <!-- /Navigation Bar Sticky -->
  <!--Breadcrumbs-->
  <ul class="breadcrumb" xmlns:v="http://rdf.data-vocabulary.org/#">
   <li typeof="v:Breadcrumb">
    <a href="/" property="v:title" rel="v:url">
     Home
    </a>
   </li>
   <li typeof="v:Breadcrumb">
    <a href="/states.php" property="v:title" rel="v:url">
     States
    </a>
   </li>
   <li class="active" typeof="v:Breadcrumb">
    <a href="/census/state/maharashtra.html" property="v:title" rel="v:url">
     Maharashtra
    </a>
   </li>
  </ul>
  <!--/Breadcrumbs-->
  <div class="topleaderboard">
   <style type="text/css">
    .adslot_lbtop{width:100%;max-height:300px}
   </style>
   <!-- censusleaderboard728 -->
   <ins class="adsbygoogle adslot_lbtop" data-ad-client="ca-pub-0612465356921996" data-ad-format="auto" data-ad-slot="2926950643" style="display:block">
   </ins>
   <script>
    (adsbygoogle=window.adsbygoogle||[]).push({});
   </script>
  </div>
  <!--Container 1st Level-->
  <div class="container-fluid">
   <h1 class="inverse">
    Maharashtra Population 2011-2018 Census
   </h1>
   <!--Row 1st Level-->
   <div class="row">
    <!--Main-Description-->
    <div class="col-sm-8">
     <br/>
     <div>
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
       <li class="active" role="presentation">
        <a aria-controls="population2011" data-toggle="tab" href="#population2011" role="tab">
         Population
        </a>
       </li>
       <li role="presentation">
        <a aria-controls="all" data-toggle="tab" href="#all" role="tab">
         History
        </a>
       </li>
       <li role="presentation">
        <a aria-controls="literacy" data-toggle="tab" href="#literacy" role="tab">
         Literacy Rate
        </a>
       </li>
       <li role="presentation">
        <a aria-controls="density" data-toggle="tab" href="#density" role="tab">
         Density
        </a>
       </li>
       <li role="presentation">
        <a aria-controls="sexratio" data-toggle="tab" href="#sexratio" role="tab">
         Sex Ratio
        </a>
       </li>
       <li role="presentation">
        <a aria-controls="futurepop" data-toggle="tab" href="#futurepop" role="tab">
         Future Population
        </a>
       </li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
       <div class="tab-pane active" id="population2011" role="tabpanel">
        <h3>
         Maharashtra Population 2011
        </h3>
        As per details from Census 2011, Maharashtra has population of 11.24 Crores, an increase from figure of 9.69 Crore in 2001 census. Total population of Maharashtra as per 2011 census is 112,374,333 of which male and female are 58,243,056 and 54,131,277 respectively. In 2001, total population was 96,878,627 in which males were 50,400,596 while females were 46,478,031. The total population growth in this decade was 15.99 percent while in previous decade it was 22.57 percent. The population of Maharashtra forms 9.28 percent of India in 2011. In 2001, the figure was 9.42 percent.
        <br/>
        <br/>
        Recently as per Maharashtra census data, 81.12% houses are owned while 15.77% were rented. In all, 69.17% couples in Maharashtra lived in single family. In 2011, 68.88% of Uttar Pradesh population had access to Banking and Non-Banking Finance Corporation. Only 5.79% of Uttar Pradesh population had internet facility which is likely to improve in 2021 due to Jio. 5.91% of family in Uttar Pradesh owned car while 24.93% owned two wheller. In few months we will also get details of election data for Maharashtra.
        <br/>
        <br/>
        <h3>
         Maharashtra Population 2018
        </h3>
        As per projection, population of Maharashtra in 2018 is 12.35 Crore.
       </div>
       <div class="tab-pane fade" id="all" role="tabpanel">
        <h3>
         Maharashtra
        </h3>
        The recently concluded 'Indian Census 2011' showed that the population of India has crossed the 1 billion mark and the population of Maharashtra is somewhere around the 110 million. Considered to be one of India's leading states in terms of revenue and contribution to the GDP, the Maharashtra Census 2011 bore some interesting results. Mumbai, a city that is considered to be the financial capital of India is part of the state of Maharashtra and has a population of over 100 million, making it the country's most populous city. Maharashtra also has other cities like Pune, Nashik and Nagpur which are more densely populated than other areas. People from different parts of India over the years have shifted to Maharashtra in general and Mumbai in particular in search of livelihood. Mumbai is one of the major metro cities in India with a widely cosmopolitan culture and a vibrant way of life.
        <br/>
        <br/>
        The Maharashtra census 2011 showed that the population of the state is growing by about 16% each year which is slightly below the national average of about 17%. The state of Maharashtra is the third largest state in the country with an area of about .3 million Sq. Km. The state is located in western India and has a long coastline to its west. The state has many places of national importance and some of the prime airports and ports in the country. Maharashtra borders the states of Gujarat, Madhya Pradesh and Karnataka. The state has a sex ratio of about 940 which is fairly equal to the national average. The state has a literacy rate of over 80% which puts it among the top states in terms of literacy.
        <br/>
        <br/>
        The Maharashtra census 2011 shows that the state is doing well in terms of literacy rate and sex ratio and continues its march towards being one of the leading states in the country.
        <br/>
        <br/>
        <h3>
         Capital City
        </h3>
        The capital city which is also the largest city in the state of Maharashtra is Mumbai.
						The languages spoken in the Maharashtra state includes Marathi. In total Maharashtra (MH) state comprises 35 districts. The ISOCODE assigned by International Organization for Standardization for Maharashtra state is MH.
       </div>
       <div class="tab-pane fade" id="literacy" role="tabpanel">
        <h3>
         Maharashtra Literacy Rate 2011
        </h3>
        Literacy rate in Maharashtra has seen upward trend and is 82.34 percent as per 2011 population census. Of that, male literacy stands at 88.38 percent while female literacy is at 75.87 percent. In 2001, literacy rate in Maharashtra stood at 76.88 percent of which male and female were 85.97 percent and 67.03 percent literate respectively.
        <br/>
        <br/>
        In actual numbers, total literates in Maharashtra stands at 81,554,290 of which males were 45,257,584 and females were 36,296,706.
       </div>
       <div class="tab-pane fade" id="density" role="tabpanel">
        <h3>
         Maharashtra Density 2011
        </h3>
        Total area of Maharashtra is 307,713 sq. km. Density of Maharashtra is 365 per sq km which is lower than national average 382 per sq km. In 2001, density of Maharashtra was 315 per sq km, while nation average in 2001 was 324 per sq km.
       </div>
       <div class="tab-pane fade" id="sexratio" role="tabpanel">
        <h3>
         Maharashtra Sex Ratio
        </h3>
        Sex Ratio in Maharashtra is 929 i.e. for each 1000 male, which is below national average of 940 as per census 2011. In 2001, the sex ratio of female was 922 per 1000 males in Maharashtra.
       </div>
       <div class="tab-pane fade" id="futurepop" role="tabpanel">
        <h3>
         Maharashtra 2019 Population
        </h3>
        What is the population of Maharashtra in 2019 ? The question though legimate has no correct answer. The last census of Maharashtra was done in 2011 and next would be in 2021. But we can do projection of future Maharashtra 2019 Population on the basis likely Population Growth Rate.
        <br/>
        <br/>
        <table class="table table-striped table-hover">
         <thead>
          <tr>
           <th>
            Year
           </th>
           <th colspan="2">
            Projected Population
           </th>
          </tr>
         </thead>
         <tbody>
          <tr>
           <td>
            2011
           </td>
           <td>
            112,374,333
           </td>
           <td>
            11.24 Crore
           </td>
          </tr>
          <tr>
           <td>
            2012
           </td>
           <td>
            113,807,248
           </td>
           <td>
            11.38 Crore
           </td>
          </tr>
          <tr>
           <td>
            2013
           </td>
           <td>
            115,229,410
           </td>
           <td>
            11.52 Crore
           </td>
          </tr>
          <tr>
           <td>
            2014
           </td>
           <td>
            116,640,546
           </td>
           <td>
            11.66 Crore
           </td>
          </tr>
          <tr class="highlight">
           <td>
            2015
           </td>
           <td>
            118,040,394
           </td>
           <td>
            11.80 Crore
           </td>
          </tr>
          <tr>
           <td>
            2016
           </td>
           <td>
            119,428,710
           </td>
           <td>
            11.94 Crore
           </td>
          </tr>
          <tr>
           <td>
            2017
           </td>
           <td>
            120,805,261
           </td>
           <td>
            12.08 Crore
           </td>
          </tr>
          <tr>
           <td>
            2018
           </td>
           <td>
            122,169,830
           </td>
           <td>
            12.22 Crore
           </td>
          </tr>
          <tr>
           <td>
            2019
           </td>
           <td>
            123,522,214
           </td>
           <td>
            12.35 Crore
           </td>
          </tr>
          <tr>
           <td>
            2020
           </td>
           <td>
            124,862,220
           </td>
           <td>
            12.49 Crore
           </td>
          </tr>
          <tr>
           <td>
            2021
           </td>
           <td>
            126,189,673
           </td>
           <td>
            12.62 Crore
           </td>
          </tr>
         </tbody>
        </table>
       </div>
      </div>
     </div>
     <br/>
     <style type="text/css">
      @media screen and (min-width:1100px){.link-md-ad728{width:728px;height:15px;margin:10px 0;clear:both}.link-md-ad468{display:none}}@media screen and (max-width:1100px){.link-md-ad728{display:none}.link-md-ad468{display:block;width:468px;height:15px;margin:10px 0;clear:both}}@media screen and (max-width:749px){.link-md-ad468{display:none}}
     </style>
     <!-- 728x15 -->
     <ins class="adsbygoogle link-md-ad728" data-ad-client="ca-pub-0612465356921996" data-ad-slot="7796531646">
     </ins>
     <script>
      (adsbygoogle=window.adsbygoogle||[]).push({});
     </script>
     <!-- 468x15 -->
     <ins class="adsbygoogle link-md-ad468" data-ad-client="ca-pub-0612465356921996" data-ad-slot="4375524641">
     </ins>
     <script>
      (adsbygoogle=window.adsbygoogle||[]).push({});
     </script>
     <!-- 468x60 middle -->
     <ins class="adsbygoogle" data-ad-client="ca-pub-0612465356921996" data-ad-format="horizontal" data-ad-slot="6864659440" style="display:block;max-width:600px;max-height:120px;">
     </ins>
     <script>
      (adsbygoogle=window.adsbygoogle||[]).push({});
     </script>
     <div class="colsdiv">
      <h3 class="collapseupdown" data-target="#table1" data-toggle="collapse">
       <span class="bfrh3 glyphicon glyphicon-menu-down">
       </span>
       Maharashtra Table Data
      </h3>
      <div class="collapse in" id="table1">
       <table class="table table1 table-striped table-hover ">
        <thead>
         <tr class="toprow" id="head">
          <th>
           Description
          </th>
          <th>
           2011
          </th>
          <th>
           2001
          </th>
         </tr>
        </thead>
        <tbody>
         <tr class="highlight">
          <td>
           Approximate Population
          </td>
          <td>
           11.24 Crores
          </td>
          <td>
           9.69 Crore
          </td>
         </tr>
         <tr>
          <td>
           Actual Population
          </td>
          <td>
           112,374,333
          </td>
          <td>
           96,878,627
          </td>
         </tr>
         <tr>
          <td>
           Male
          </td>
          <td>
           58,243,056
          </td>
          <td>
           50,400,596
          </td>
         </tr>
         <tr>
          <td>
           Female
          </td>
          <td>
           54,131,277
          </td>
          <td>
           46,478,031
          </td>
         </tr>
         <tr class="highlight">
          <td>
           Population Growth
          </td>
          <td>
           15.99%
          </td>
          <td>
           22.57%
          </td>
         </tr>
         <tr>
          <td>
           Percantage of total Population
          </td>
          <td>
           9.28%
          </td>
          <td>
           9.42%
          </td>
         </tr>
         <tr class="highlight">
          <td>
           Sex Ratio
          </td>
          <td>
           929
          </td>
          <td>
           922
          </td>
         </tr>
         <tr>
          <td>
           Child Sex Ratio
          </td>
          <td>
           894

bs4.BeautifulSoup

In [4]:
all=soup.find_all("table",{"class","table table1 table-striped table-hover "})
#print all
print type(all)

<class 'bs4.element.ResultSet'>

In [5]:
print all

[<table class="table table1 table-striped table-hover ">\n<thead>\n<tr class="toprow" id="head">\n<th>Description</th>\n<th>2011</th>\n<th>2001</th>\n</tr>\n</thead>\n<tbody>\n<tr class="highlight">\n<td>Approximate Population</td>\n<td>11.24 Crores</td>\n<td>9.69 Crore</td>\n</tr>\n<tr>\n<td>Actual Population</td>\n<td>112,374,333</td>\n<td>96,878,627</td>\n</tr>\n<tr>\n<td>Male</td>\n<td>58,243,056</td>\n<td>50,400,596</td>\n</tr>\n<tr>\n<td>Female</td>\n<td>54,131,277</td>\n<td>46,478,031</td>\n</tr>\n<tr class="highlight">\n<td>Population Growth</td>\n<td>15.99%</td>\n<td>22.57%</td>\n</tr>\n<tr>\n<td>Percantage of total Population</td>\n<td>9.28%</td>\n<td>9.42%</td>\n</tr>\n<tr class="highlight">\n<td>Sex Ratio</td>\n<td>929</td>\n<td>922</td>\n</tr>\n<tr>\n<td>Child Sex Ratio</td>\n<td>894</td>\n<td>913</td>\n</tr>\n<tr>\n<td colspan="99">\n<ins class="adsbygoogle" data-ad-client="ca-pub-0612465356921996" data-ad-format="fluid" data-ad-layout-key="-fg+5m+7r-g6+16" data-ad-slot="1087380887" style="display:block;max-width:500px;"></ins>\n<script>(adsbygoogle=window.adsbygoogle||[]).push({});</script>\n</td>\n</tr>\n<tr class="highlight">\n<td>Density/km2</td>\n<td>365</td>\n<td>315</td>\n</tr>\n<tr>\n<td>Density/mi2</td>\n<td>946</td>\n<td>815</td>\n</tr>\n<tr>\n<td>Area(Km<sup>2</sup>)</td>\n<td>307,713</td>\n<td>307,713</td>\n</tr>\n<tr>\n<td>Area mi2</td>\n<td>118,809</td>\n<td>118,809</td>\n</tr>\n<tr>\n<td>Total Child Population (0-6 Age)</td>\n<td>13,326,517</td>\n<td>13,671,126</td>\n</tr>\n<tr>\n<td>Male Population (0-6 Age)</td>\n<td>7,035,391</td>\n<td>7,146,432</td>\n</tr>\n<tr>\n<td>Female Population (0-6 Age)</td>\n<td>6,291,126</td>\n<td>6,524,694</td>\n</tr>\n<tr class="highlight">\n<td>Literacy</td>\n<td>82.34 %</td>\n<td>76.88 %</td>\n</tr>\n<tr>\n<td>Male Literacy</td>\n<td>88.38 %</td>\n<td>85.97 %</td>\n</tr>\n<tr>\n<td>Female Literacy</td>\n<td>75.87 %</td>\n<td>67.03 %</td>\n</tr>\n<tr>\n<td>Total Literate</td>\n<td>81,554,290</td>\n<td>63,965,943</td>\n</tr>\n<tr>\n<td>Male Literate</td>\n<td>45,257,584</td>\n<td>37,184,963</td>\n</tr>\n<tr>\n<td>Female Literate</td>\n<td>36,296,706</td>\n<td>26,780,980</td>\n</tr>\n</tbody>\n</table>, <table class="table table1 table-striped table-hover ">\n<thead>\n<tr>\n<th>Description</th>\n<th>Population</th>\n<th>Percentage</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Hindu</td>\n<td>89,703,057</td>\n<td>79.83 %</td>\n</tr>\n<tr>\n<td>Muslim</td>\n<td>12,971,152</td>\n<td>11.54 %</td>\n</tr>\n<tr>\n<td>Buddhist</td>\n<td>6,531,200</td>\n<td>5.81 %</td>\n</tr>\n<tr>\n<td>Jain</td>\n<td>1,400,349</td>\n<td>1.25 %</td>\n</tr>\n<tr>\n<td>Christian</td>\n<td>1,080,073</td>\n<td>0.96 %</td>\n</tr>\n<tr>\n<td>Not Available</td>\n<td>286,290</td>\n<td>0.25 %</td>\n</tr>\n<tr>\n<td>Sikh</td>\n<td>223,247</td>\n<td>0.20 %</td>\n</tr>\n<tr>\n<td>Other Religion</td>\n<td>178,965</td>\n<td>0.16 %</td>\n</tr>\n</tbody>\n</table>, <table class="table table1 table-striped table-hover ">\n<thead>\n<tr>\n<th>Description</th>\n<th>Rural</th>\n<th>Urban</th>\n</tr>\n</thead>\n<tbody>\n<tr class="highlight">\n<td>Population (%)</td>\n<td>54.78 %</td>\n<td>45.22 %</td>\n</tr>\n<tr>\n<td>Total Population</td>\n<td>61,556,074</td>\n<td>50,818,259</td>\n</tr>\n<tr>\n<td>Male Population</td>\n<td>31,539,034</td>\n<td>26,704,022</td>\n</tr>\n<tr>\n<td>Female Population</td>\n<td>30,017,040</td>\n<td>24,114,237</td>\n</tr>\n<tr class="highlight">\n<td>Population Growth</td>\n<td>10.36 %</td>\n<td>23.64 %</td>\n</tr>\n<tr class="highlight">\n<td>Sex Ratio</td>\n<td>952</td>\n<td>903</td>\n</tr>\n<tr>\n<td>Child Sex Ratio (0-6)</td>\n<td>890</td>\n<td>899</td>\n</tr>\n<tr>\n<td>Child Population (0-6)</td>\n<td>7,688,954</td>\n<td>5,637,563</td>\n</tr>\n<tr class="highlight">\n<td>Child Percentage (0-6)</td>\n<td>12.49 %</td>\n<td>11.09 %</td>\n</tr>\n<tr>\n<td>Literates</td>\n<td>41,482,761</td>\n<td>40,071,529</td>\n</tr>\n<tr class="highlight">\n<td>Average Literacy</td>\n<td>77.01 %</td>\n<td>88.69 %</td>\n</tr>\n<tr>\n<td>Male Literacy</td>\n<td>85.15 %</td>\n<td>92.12 %</td>\n</tr>\n<tr>\n<td>Female Literacy</td>\n<td>64.80 %</td>\n<td>75.75 %</td>\n</tr>\n</tbody>\n</table>, <table class="table table1 table-striped table-hover ">\n<thead>\n<tr>\n<th>Big Cities</th>\n<th>Population</th>\n<th>Male</th>\n<th>Female</th>\n</tr>\n</thead>\n<tbody>\n<tr class="tr1">\n<td><a href="/census/city/365-mumbai.html" title="Mumbai">Mumbai</a> (Municipal Corporation)</td>\n<td>12,442,373</td>\n<td>6,715,931</td>\n<td>5,726,442</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/city/375-pune.html" title="Pune">Pune</a> (Municipal Corporation)</td>\n<td>3,124,458</td>\n<td>1,603,675</td>\n<td>1,520,783</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/city/353-nagpur.html" title="Nagpur">Nagpur</a> (Municipal Corporation)</td>\n<td>2,405,665</td>\n<td>1,225,405</td>\n<td>1,180,260</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/city/367-thane.html" title="Thane">Thane</a> (Municipal Corporation)</td>\n<td>1,841,488</td>\n<td>975,399</td>\n<td>866,089</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/city/376-pimpri-and-chinchwad.html" title="Pimpri and Chinchwad">Pimpri and Chinchwad</a> (Municipal Corporation)</td>\n<td>1,727,692</td>\n<td>942,533</td>\n<td>785,159</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/city/361-nashik.html" title="Nashik">Nashik</a> (Municipal Corporation)</td>\n<td>1,486,053</td>\n<td>782,517</td>\n<td>703,536</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/city/369-kalyan-and-dombivali.html" title="Kalyan and Dombivali">Kalyan and Dombivali</a> (Municipal Corporation)</td>\n<td>1,247,327</td>\n<td>649,626</td>\n<td>597,701</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/city/363-vasai-virar.html" title="Vasai Virar">Vasai Virar</a> (Municipal Corporation)</td>\n<td>1,222,390</td>\n<td>648,172</td>\n<td>574,218</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/city/360-aurangabad.html" title="Aurangabad">Aurangabad</a> (Municipal Corporation)</td>\n<td>1,175,116</td>\n<td>609,206</td>\n<td>565,910</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/city/368-navi-mumbai.html" title="Navi Mumbai">Navi Mumbai</a> (Municipal Corporation)</td>\n<td>1,120,547</td>\n<td>610,060</td>\n<td>510,487</td>\n</tr>\n</tbody>\n</table>, <table class="table table1 table-striped table-hover ">\n<thead>\n<tr>\n<th>Large Metropolitan Region</th>\n<th>Population</th>\n<th>Male</th>\n<th>Female</th>\n</tr>\n</thead>\n<tbody>\n<tr class="tr1">\n<td><a href="/census/metropolitan/305-mumbai.html" title="Mumbai">Mumbai</a></td>\n<td>18,394,912</td>\n<td>9,872,271</td>\n<td>8,522,641</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/metropolitan/306-pune.html" title="Pune">Pune</a></td>\n<td>5,057,709</td>\n<td>2,656,240</td>\n<td>2,401,469</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/metropolitan/307-nagpur.html" title="Nagpur">Nagpur</a></td>\n<td>2,497,870</td>\n<td>1,274,138</td>\n<td>1,223,732</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/metropolitan/308-nashik.html" title="Nashik">Nashik</a></td>\n<td>1,561,809</td>\n<td>821,921</td>\n<td>739,888</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/metropolitan/310-aurangabad.html" title="Aurangabad">Aurangabad</a></td>\n<td>1,193,167</td>\n<td>618,845</td>\n<td>574,322</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/metropolitan/312-bhiwandi.html" title="Bhiwandi">Bhiwandi</a></td>\n<td>735,681</td>\n<td>431,704</td>\n<td>303,977</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/metropolitan/314-malegaon.html" title="Malegaon">Malegaon</a></td>\n<td>576,642</td>\n<td>293,402</td>\n<td>283,240</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/metropolitan/315-kolhapur.html" title="Kolhapur">Kolhapur</a></td>\n<td>561,837</td>\n<td>286,938</td>\n<td>274,899</td>\n</tr>\n<tr class="tr1">\n<td><a href="/census/metropolitan/317-sangli.html" title="Sangli">Sangli</a></td>\n<td>513,961</td>\n<td>259,320</td>\n<td>254,641</td>\n</tr>\n</tbody>\n</table>]

In [6]:
datav=all[1].find_all("td")
print datav[1].text

89,703,057

In [7]:
l=[]
for k in range(8):
    b={}
    k=k*3
    b["Description"]= datav[k].text
    b["Population"]= datav[k+1].text
    b["Percentage"]= datav[k+2].text
    l.append(b)

In [8]:
import pandas as pd
df=pd.DataFrame(l)
#data=df.drop(19)
print df

      Description Percentage  Population
0           Hindu    79.83 %  89,703,057
1          Muslim    11.54 %  12,971,152
2        Buddhist     5.81 %   6,531,200
3            Jain     1.25 %   1,400,349
4       Christian     0.96 %   1,080,073
5   Not Available     0.25 %     286,290
6            Sikh     0.20 %     223,247
7  Other Religion     0.16 %     178,965

In [9]:
df.to_csv('output.csv')

In [10]:
ndata=pd.read_csv('output.csv')

In [11]:
ndata

   Unnamed: 0     Description Percentage  Population
0           0           Hindu    79.83 %  89,703,057
1           1          Muslim    11.54 %  12,971,152
2           2        Buddhist     5.81 %   6,531,200
3           3            Jain     1.25 %   1,400,349
4           4       Christian     0.96 %   1,080,073
5           5   Not Available     0.25 %     286,290
6           6            Sikh     0.20 %     223,247
7           7  Other Religion     0.16 %     178,965